// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TESTINTERVIEW.Data;

namespace TESTINTERVIEW.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TESTINTERVIEW.Data.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MovieDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieDirectort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieRuntime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MovieYear")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("TESTINTERVIEW.Data.MovieStars", b =>
                {
                    b.Property<int>("MovieStarsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("MovieStarsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieStarsId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieStars");
                });

            modelBuilder.Entity("TESTINTERVIEW.Data.MovieStars", b =>
                {
                    b.HasOne("TESTINTERVIEW.Data.Movie", null)
                        .WithMany("MovieStars")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("TESTINTERVIEW.Data.Movie", b =>
                {
                    b.Navigation("MovieStars");
                });
#pragma warning restore 612, 618
        }
    }
}
